name: Test workflow
on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test process
    runs-on: ubuntu-latest
    environment:
      name: development

    steps:
      - shell: bash
        run: |
          echo "${PIPPO}" > pippo.txt"
          cat "pippo.txt"
        env:
          PIPPO: ${{ secrets.PIPPO }}
      - shell: bash
        run: |
          echo "${PLUTO}" > "pluto.txt"
          cat "pluto.txt"
        env:
          PLUTO: ${{ secrets.PLUTO }}
