name: Test workflow
on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test process
    runs-on: ubuntu-latest
    environment:
      name: development

    steps:
      - run: curl "ftp://${FTP_HOST}/" --user "${FTP_USER}:${FTP_PASS}"
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
